// Decompiled with JetBrains decompiler
// Type: Magicka.Decal
// Assembly: Magicka, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null
// MVID: 20B30093-0B41-4B13-B130-C3B04DD4E3C2
// Assembly location: C:\SteamLibrary\steamapps\common\Magicka\Magicka.exe

#nullable disable
namespace Magicka;

public enum Decal
{
  BloodRegular0,
  BloodRegular1,
  BloodRegular2,
  BloodRegular3,
  BloodGreen0,
  BloodGreen1,
  BloodGreen2,
  BloodGreen3,
  BloodBlack0,
  BloodBlack1,
  BloodBlack2,
  BloodBlack3,
  BloodWood0,
  BloodWood1,
  BloodWood2,
  BloodWood3,
  BloodInsect0,
  BloodInsect1,
  BloodInsect2,
  BloodInsect3,
  Scorched,
  Crater,
  Cold,
  Water,
  LifeGround,
  ArcaneGround,
  BuffOffensive,
  BuffDefensive,
  BuffSpecial,
  AuraOffensive,
  AuraDefensive,
  AuraSpecial,
  Grease,
  MagickCircle,
  MagickBurn,
  Cracks,
  Reserved_4_4,
  Reserved_4_5,
  Reserved_4_6,
  Reserved_4_7,
  Reserved_5_0,
  Reserved_5_1,
  Reserved_5_2,
  Reserved_5_3,
  Reserved_5_4,
  Reserved_5_5,
  Reserved_5_6,
  Reserved_5_7,
  Reserved_6_0,
  Reserved_6_1,
  Reserved_6_2,
  Reserved_6_3,
  Reserved_6_4,
  Reserved_6_5,
  Reserved_6_6,
  Reserved_6_7,
  Reserved_7_0,
  Reserved_7_1,
  Reserved_7_2,
  Reserved_7_3,
  Reserved_7_4,
  Reserved_7_5,
  Reserved_7_6,
  TestPattern,
}
